In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.special as special 
from scipy.optimize import curve_fit
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [10]:
#Cargar archivo csv des seaborn

# Verificar sin indice 
df= pd.read_csv('DATANN.csv')
df

Unnamed: 0  Administrador  Usuario  botón correcto  \
0              0              1        2             1.0   
1              1              1        2             0.0   
2              2              1        2             1.0   
3              3              1        2             0.0   
4              4              1        2             0.0   
...          ...            ...      ...             ...   
5860        5860              0       30             1.0   
5861        5861              0        3             0.0   
5862        5862              0        3             0.0   
5863        5863              0        3             0.0   
5864        5864              0        3             0.0   

      tiempo de interacción  mini juego  número de interacción  \
0                  5.399169           8                    1.0   
1                  1.283400           8                    2.0   
2                  2.700226           8                    3.0   
3                  3.050262           8                    4.0   
4                  4.750256           8                    5.0   
...                     ...         ...                    ...   
5860               7.099429           1                    4.0   
5861               2.135419           0                    1.0   
5862               2.135419           0                    1.0   
5863               2.135419           0                    1.0   
5864               2.135419          10                    1.0   

      color presionado  dificultad  Juego  auto push  tiempo de lección  \
0                    3           0      0        0.0           0.000000   
1                    0           0      0        0.0           0.000000   
2                    1           0      0        0.0           0.000000   
3                    1           0      0        0.0           0.000000   
4                    1           0      0        0.0           0.000000   
...                ...         ...    ...        ...                ...   
5860                 1           0      0        0.0           7.461668   
5861                 1           2      0        0.0           0.000000   
5862                 1           2      0        0.0           2.271806   
5863                 1           2      0        0.0           2.271806   
5864                 1           2      0        0.0           2.271806   

      tiempo de sesión  
0             0.000000  
1             0.000000  
2             0.000000  
3             0.000000  
4             0.000000  
...                ...  
5860        332.240000  
5861          0.000000  
5862          0.000000  
5863          6.478299  
5864          6.478299  

[5865 rows x 13 columns]

In [11]:
df10= df.groupby(['botón correcto'])['botón correcto'].count()
df10.info

<bound method Series.info of botón correcto
0.0    2668
1.0    3197
Name: botón correcto, dtype: int64>

### Correlación Lógistica

In [12]:
#verificar los valores sin repetirse de una columna
unico = np.unique(df['botón correcto'])
unico

array([0., 1.])

## Botón correcto

In [13]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=df[['mini juego', 'Juego', 'número de interacción']]
vars_Dep=df[['botón correcto']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =0)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('sensibilidad del modelo: ')
print(sensibilidad)


Matriz de confusión: 
[[347 445]
 [181 787]]

precision del modelo: 
0.6571969696969697

exactitud del modelo
0.6443181818181818

sensibilidad del modelo: 
0.43813131313131315


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Juego

In [59]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=df[['Usuario', 'mini juego', 'color presionado']]
vars_Dep=df[['Juego']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =1)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('sensibilidad del modelo: ')
print(sensibilidad)


Matriz de confusión: 
[[1069   86]
 [   3  602]]

precision del modelo: 
0.875

exactitud del modelo
0.9494318181818182

sensibilidad del modelo: 
0.9950413223140496


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Auto push

In [15]:
#verificar los valores sin repetirse de una columna
unico = np.unique(df['auto push'])
unico

array([0., 1.])

In [60]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=df[['Usuario', 'mini juego', 'color presionado']]
vars_Dep=df[['auto push']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =0)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('sensibilidad del modelo: ')
print(sensibilidad)


Matriz de confusión: 
[[1314  427]
 [   4   15]]

precision del modelo: 
0.9969650986342944

exactitud del modelo
0.7551136363636364

sensibilidad del modelo: 
0.7547386559448592


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## Colores

In [17]:
copy1 = df.copy()
copy2 = df.copy()
copy3 = df.copy()
copy4 = df.copy()
copy5 = df.copy()

In [18]:
#verificar los valores sin repetirse de una columna
unico = np.unique(df['color presionado'])
unico

array([0, 1, 2, 3, 5])

In [19]:
copy1['color presionado']= copy1['color presionado'].replace([1,2,3,5], 6)

copy2['color presionado']= copy2['color presionado'].replace([0,2,3,5], 6)

copy3['color presionado']= copy3['color presionado'].replace([0,1,3,5], 6)

copy4['color presionado']= copy4['color presionado'].replace([0,1,2,5], 6)

copy5['color presionado']= copy5['color presionado'].replace([0,1,2,3], 6)

print(copy1['color presionado'].unique())
print(copy2['color presionado'].unique())
print(copy3['color presionado'].unique())
print(copy4['color presionado'].unique())
print(copy5['color presionado'].unique())


[6 0]
[6 1]
[6 2]
[3 6]
[6 5]


***Violet***

In [20]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=copy1[['botón correcto', 'número de interacción', 'tiempo de interacción']]
vars_Dep=copy1[['color presionado']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =0)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=0)
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[183 303]
 [363 911]]

precision del modelo: 
0.33516483516483514

exactitud del modelo
0.6215909090909091

sensibilidad del modelo: 
0.3765432098765432


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


***Green***

In [21]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=copy2[['botón correcto', 'número de interacción', 'tiempo de interacción']]
vars_Dep=copy2[['color presionado']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =1)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=1)
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[297 138]
 [831 494]]

precision del modelo: 
0.2632978723404255

exactitud del modelo
0.44943181818181815

sensibilidad del modelo: 
0.6827586206896552


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


***Yellow***

In [22]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=copy3[['botón correcto', 'número de interacción', 'tiempo de interacción']]
vars_Dep=copy3[['color presionado']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =2)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=2)
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[294 108]
 [879 479]]

precision del modelo: 
0.2506393861892583

exactitud del modelo
0.43920454545454546

sensibilidad del modelo: 
0.7313432835820896


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


***Blue***

In [23]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=copy4[['botón correcto', 'número de interacción', 'tiempo de interacción']]
vars_Dep=copy4[['color presionado']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =3)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=3)
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[302 104]
 [964 390]]

precision del modelo: 
0.23854660347551343

exactitud del modelo
0.3931818181818182

sensibilidad del modelo: 
0.7438423645320197


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


***Red***

In [24]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=copy5[['botón correcto', 'número de interacción', 'tiempo de interacción']]
vars_Dep=copy5[['color presionado']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label =5)
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label=5)
print('sensibilidad del modelo: ')
print(sensibilidad)

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Matriz de confusión: 
[[  12    0]
 [ 394 1354]]

precision del modelo: 
0.029556650246305417

exactitud del modelo
0.7761363636363636

sensibilidad del modelo: 
1.0


## Dificultad

**Convertir a dicotómica**

In [25]:
copia1 = df.copy()
copia2= df.copy()
copia3=df.copy()
copia4=df.copy()

In [26]:
#Verificar los valores sin repetirse de una columna
unico = np.unique(copia1['dificultad'])
unico

array([0, 1, 2, 3])

In [27]:
#Convertimos una variable categórica a dicotómica 
copia1 ['dificultad']= copia1['dificultad'].replace([0,1],'Niveles básicos')
copia1 ['dificultad']= copia1['dificultad'].replace([2,3],'Niveles avanzados')

In [28]:
#Declaramos las variables dependientes e independientes para regresión logística
#Dependiente es dicotómica y las independientes de tipo numérico
Vars_Indep = copia1[['tiempo de interacción','mini juego','Juego']] #numérica
Var_Dep = copia1['dificultad'] #dicotómica

#Redefinir
X = Vars_Indep
y = Var_Dep

#Dividimos el conjunto de datos en entrenamiento y prueba
#test size es que queremos el 30%, podemos irle cambiando
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.3, random_state =None) #Va a asignar aleatoriamente 

In [29]:
#Se escalan los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algortimo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced') #

#Emtrenamos el modelo
algoritmo.fit(X_train,y_train)
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Niveles avanzados', 'Niveles básicos', 'Niveles avanzados', ...,
       'Niveles avanzados', 'Niveles avanzados', 'Niveles avanzados'],
      shape=(1760,), dtype=object)

In [30]:
#Verifico la matriz de confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix (y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

#Calculo la precisión Variable 1
from sklearn.metrics import precision_score
#Etiqueta de alive es yes y no
precision = precision_score(y_test,y_pred,average='binary',pos_label='Niveles básicos') 
print('Precisión del modelo Nivel básicos:')
print(precision)

#Calculo la precisión Variable 2
from sklearn.metrics import precision_score
#Etiqueta de alive es yes y no
precision = precision_score(y_test,y_pred,average='binary',pos_label='Niveles avanzados') 
print('Precisión del modelo Niveles avanzados:')
print(precision)

#Calculo la exactitud
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test,y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test,y_pred, average ='binary',pos_label='Niveles básicos')
print('Sensibilidad del modelo Nivel básicos:')
print(sensibilidad)

#Calculo la sensibilidad del modelo
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test,y_pred, average ='binary',pos_label='Niveles avanzados')
print('Sensibilidad del modelo Nivel avanzados:')
print(sensibilidad)

Matriz de Confusión
[[381 246]
 [555 578]]
Precisión del modelo Nivel básicos:
0.7014563106796117
Precisión del modelo Niveles avanzados:
0.40705128205128205
Exactitud del modelo:
0.5448863636363637
Sensibilidad del modelo Nivel básicos:
0.5101500441306267
Sensibilidad del modelo Nivel avanzados:
0.6076555023923444


**Conclusión**

De todas las veces que el modelo predijo “Niveles básicos”, acertó un 70.6%. Cuando el modelo ve patrones claros de comportamiento “básico” (como tiempos cortos o más aciertos), generalmente tiene razón.
La exactitud representa el porcentaje total de aciertos, el cual 54% representa que esa fue la cantidad de porcentaje total, pero no es buena en modelos desbalanceados.
De todos los que sí eran “Niveles básicos”, el modelo solo detectó correctamente un 52.9%.


## Minijuegos

***Asteroides***

**Convertir a dicotómica**

In [31]:
#Verificar los valores sin repetirse de una columna
unico = np.unique(copia2['mini juego'])
unico

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13])

In [32]:
#Convertimos una variable categórica a dicotómica 
copia2 ['mini juego']= copia2['mini juego'].replace([ 0,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13],'Mini Juego tipo B')
copia2 ['mini juego']= copia2['mini juego'].replace(1,'Asteroides')

In [33]:
#Declaramos las variables dependientes e independientes para regresión logística
#Dependiente es dicotómica y las independientes de tipo numérico
Vars_Indep = copia2[['botón correcto','tiempo de interacción','Juego']] #numérica
Var_Dep = copia2['mini juego'] #dicotómica

#Redefinir
X = Vars_Indep
y = Var_Dep

#Dividimos el conjunto de datos en entrenamiento y prueba
#test size es que queremos el 30%, podemos irle cambiando
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.3, random_state =None) #Va a asignar aleatoriamente 

In [34]:
#Se escalan los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algortimo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced') #

#Emtrenamos el modelo
algoritmo.fit(X_train,y_train)
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Mini Juego tipo B', 'Mini Juego tipo B', 'Mini Juego tipo B', ...,
       'Asteroides', 'Mini Juego tipo B', 'Mini Juego tipo B'],
      shape=(1760,), dtype=object)

In [35]:
#Verifico la matriz de confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix (y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

#Calculo la precisión Var 1
from sklearn.metrics import precision_score
#Etiqueta de alive es yes y no
precision = precision_score(y_test,y_pred,average='binary',pos_label='Asteroides') 
print('Precisión del modelo Asteroides:')
print(precision)

#Calculo la precisión Var 2
from sklearn.metrics import precision_score
#Etiqueta de alive es yes y no
precision = precision_score(y_test,y_pred,average='binary',pos_label='Mini Juego tipo B') 
print('Precisión del modelo Mini Juego tipo B:')
print(precision)

#Calculo la exactitud
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test,y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo Var 1
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test,y_pred, average ='binary',pos_label='Asteroides')
print('Sensibilidad del modelo Asteroides:')
print(sensibilidad)

#Calculo la sensibilidad del modelo Var 2
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test,y_pred, average ='binary',pos_label='Mini Juego tipo B')
print('Sensibilidad del modelo Mini Juego tipo B:')
print(sensibilidad)

Matriz de Confusión
[[218  53]
 [585 904]]
Precisión del modelo Asteroides:
0.2714819427148194
Precisión del modelo Mini Juego tipo B:
0.9446185997910136
Exactitud del modelo:
0.6375
Sensibilidad del modelo Asteroides:
0.8044280442804428
Sensibilidad del modelo Mini Juego tipo B:
0.6071188717259905


**Conclusión**

El modelo identifica bien cuando una sesión es realmente “Asteroides” (alta sensibilidad), aunque aún se confunde con casos que no lo son (precisión baja).
El modelo aprende a reconocer “Asteroides” porque las personas que lo juegan se comportan de forma más o menos parecida: responden rápido, presionan ciertos botones, están en cierto entorno. Pero como hay otros juegos donde los usuarios también actúan parecido, el modelo se confunde y etiqueta mal. Aun así, el contexto del juego (Juego) le da al modelo una ventaja extra, como si le soplaran la respuesta.


***Despegue***

**Convertir a dicotómica**

In [36]:
#Verificar los valores sin repetirse de una columna
unico = np.unique(copia3['mini juego'])
unico

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8, 10, 11, 12, 13])

In [37]:
#Convertimos una variable categórica a dicotómica 
copia3 ['mini juego']= copia3['mini juego'].replace([ 3,  1,  2,  4,  5,  6,  7,  8, 10, 11, 12, 13],'Mini Juego tipo A')
copia3 ['mini juego']= copia3['mini juego'].replace(0,'Despegue')

In [38]:
#Declaramos las variables dependientes e independientes para regresión logística
#Dependiente es dicotómica y las independientes de tipo numérico
#Vars_Indep = copia3[['Usuario','tiempo de interacción','Juego']] #numérica
Vars_Indep = copia3[['botón correcto','tiempo de interacción','Juego']] #numérica
Var_Dep = copia3['mini juego'] #dicotómica

#Redefinir
X = Vars_Indep
y = Var_Dep

#Dividimos el conjunto de datos en entrenamiento y prueba
#test size es que queremos el 30%, podemos irle cambiando
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.3, random_state =None) #Va a asignar aleatoriamente 

In [39]:
#Se escalan los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algortimo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced') #

#Emtrenamos el modelo
algoritmo.fit(X_train,y_train)
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Mini Juego tipo A', 'Despegue', 'Despegue', ..., 'Despegue',
       'Despegue', 'Despegue'], shape=(1760,), dtype=object)

In [40]:
#Verifico la matriz de confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix (y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

#Calculo la precisión Var 1
from sklearn.metrics import precision_score
#Etiqueta de alive es yes y no
precision = precision_score(y_test,y_pred,average='binary',pos_label='Despegue') 
print('Precisión del modelo Despegue:')
print(precision)

#Calculo la precisión Var 2
from sklearn.metrics import precision_score
#Etiqueta de alive es yes y no
precision = precision_score(y_test,y_pred,average='binary',pos_label='Mini Juego tipo A') 
print('Precisión del modelo Mini Juego tipo A:')
print(precision)

#Calculo la exactitud
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test,y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo Var 1
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test,y_pred, average ='binary',pos_label='Despegue')
print('Sensibilidad del modelo Despegue:')
print(sensibilidad)

#Calculo la sensibilidad del modelo Var 1
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test,y_pred, average ='binary',pos_label='Mini Juego tipo A')
print('Sensibilidad del modelo Mini Juego tipo A:')
print(sensibilidad)

Matriz de Confusión
[[300  16]
 [629 815]]
Precisión del modelo Despegue:
0.32292787944025836
Precisión del modelo Mini Juego tipo A:
0.9807460890493381
Exactitud del modelo:
0.6335227272727273
Sensibilidad del modelo Despegue:
0.9493670886075949
Sensibilidad del modelo Mini Juego tipo A:
0.564404432132964


**Conclusión**

Despegue es hasta el mejor minijuego para modelar: mantiene una alta sensibilidad, pero con una mejor precisión que Asteroide.
Solo 12 falsos positivos indica que el modelo es confiable cuando predice esta clase.
Este parece ser el más fácil de reconocer para el modelo, no solo porque los números son buenos, sino porque los usuarios que lo juegan lo hacen de forma muy parecida entre sí. Eso significa que, cuando alguien entra a Despegue, tiende a jugarlo de una manera consistente, ya sea en el tiempo que tarda, en la forma en que responde (botón correcto) o en el entorno (Juego) en el que aparece.


## Número de interacciones

**Convertir a dicotómica**

In [41]:
#Limite superior e inferior de columna objetivo age
Max = copia4['número de interacción'].max()
Min = copia4['número de interacción'].min()
Limites =[Min,Max]
Limites

[np.float64(1.0), np.float64(256.0)]

In [42]:
#Intervalos
intervalos = np.linspace(0.9,256.1,3) #se agrega un decimal mas/menos para que agarre el rango
intervalos

array([  0.9, 128.5, 256.1])

In [43]:
#Creamos las categorías
categorias = ['Interacciones del 1 al 128','Interacciones del 129 al 256']
#Ajustar maximo de filas
pd.options.display.max_rows = None
#Finalmente creamos las categorías en la columna numérica
copia4['número de interacción']= pd.cut(x=copia4['número de interacción'],bins= intervalos,labels=categorias)
copia4['número de interacción']

0         Interacciones del 1 al 128
1         Interacciones del 1 al 128
2         Interacciones del 1 al 128
3         Interacciones del 1 al 128
4         Interacciones del 1 al 128
5         Interacciones del 1 al 128
6         Interacciones del 1 al 128
7         Interacciones del 1 al 128
8         Interacciones del 1 al 128
9         Interacciones del 1 al 128
10        Interacciones del 1 al 128
11        Interacciones del 1 al 128
12        Interacciones del 1 al 128
13        Interacciones del 1 al 128
14        Interacciones del 1 al 128
15        Interacciones del 1 al 128
16        Interacciones del 1 al 128
17        Interacciones del 1 al 128
18        Interacciones del 1 al 128
19        Interacciones del 1 al 128
20        Interacciones del 1 al 128
21        Interacciones del 1 al 128
22        Interacciones del 1 al 128
23        Interacciones del 1 al 128
24        Interacciones del 1 al 128
25        Interacciones del 1 al 128
26        Interacciones del 1 al 128
2

In [44]:
#Declaramos las variables dependientes e independientes para regresión logística
#Dependiente es dicotómica y las independientes de tipo numérico
Vars_Indep = copia4[['color presionado','tiempo de interacción']] #numérica
Var_Dep = copia4['número de interacción'] #dicotómica

#Redefinir
X = Vars_Indep
y = Var_Dep

#Dividimos el conjunto de datos en entrenamiento y prueba
#test size es que queremos el 30%, podemos irle cambiando
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = 0.3, random_state =None) #Va a asignar aleatoriamente 

In [45]:
#Se escalan los datos
escalar = StandardScaler()

X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algortimo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced') #

#Emtrenamos el modelo
algoritmo.fit(X_train,y_train)
#Realizamos una predicción
y_pred = algoritmo.predict(X_test)
y_pred

array(['Interacciones del 1 al 128', 'Interacciones del 1 al 128',
       'Interacciones del 1 al 128', ..., 'Interacciones del 1 al 128',
       'Interacciones del 1 al 128', 'Interacciones del 129 al 256'],
      shape=(1760,), dtype=object)

In [46]:
#Verifico la matriz de confunsión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix (y_test, y_pred)
print('Matriz de Confusión')
print(matriz)

#Calculo la precisión Var 1
from sklearn.metrics import precision_score
#Etiqueta de alive es yes y no
precision = precision_score(y_test,y_pred,average='binary',pos_label='Interacciones del 1 al 128') 
print('Precisión del modelo Interacciones del 1 al 128:')
print(precision)

#Calculo la precisión Var 2
from sklearn.metrics import precision_score
#Etiqueta de alive es yes y no
precision = precision_score(y_test,y_pred,average='binary',pos_label='Interacciones del 129 al 256') 
print('Precisión del modelo Interacciones del 129 al 256:')
print(precision)

#Calculo la exactitud
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test,y_pred)
print('Exactitud del modelo:')
print(exactitud)

#Calculo la sensibilidad del modelo Var 1
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test,y_pred, average ='binary',pos_label='Interacciones del 1 al 128')
print('Sensibilidad del modelo Interacciones del 1 al 128:')
print(sensibilidad)

#Calculo la sensibilidad del modelo Var 2
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test,y_pred, average ='binary',pos_label='Interacciones del 129 al 256')
print('Sensibilidad del modelo Interacciones del 129 al 256:')
print(sensibilidad)

Matriz de Confusión
[[1593  125]
 [   2   40]]
Precisión del modelo Interacciones del 1 al 128:
0.9987460815047022
Precisión del modelo Interacciones del 129 al 256:
0.24242424242424243
Exactitud del modelo:
0.9278409090909091
Sensibilidad del modelo Interacciones del 1 al 128:
0.9272409778812573
Sensibilidad del modelo Interacciones del 129 al 256:
0.9523809523809523


**Conclusión**

El modelo logró predecir con mucha precisión cuándo un usuario realizó pocas o muchas interacciones dentro del minijuego. Esto demuestra que el comportamiento del usuario sí cambia en función del número total de intentos, y que esas diferencias son detectables por el modelo usando solo variables simples como color y tiempo.
Eso sugiere que los usuarios que hacen pocas interacciones se comportan de forma muy distinta a los que hacen muchas. Tal vez quienes interactúan poco resuelven rápido, no se equivocan tanto, o usan colores más definidos. Mientras que quienes interactúan más pasan más tiempo, cometen más errores o exploran más.

## usuarios

In [47]:
usuario_1=df.copy()
usuario_2=df.copy()
usuario_3=df.copy()
usuario_4=df.copy()
usuario_5=df.copy()

In [48]:
#verificar los valores sin repetirse de una columna
unico = np.unique(usuario_1['Usuario'])
unico

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

### Valentín 

In [49]:
#convertimos una variable categorica  dicotomica
usuario_1['Usuario']= usuario_1['Usuario'].replace([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_1['Usuario']= usuario_1['Usuario'].replace([12], 'Valentin')


In [61]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_1[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_1[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='demás usuarios')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='demás usuarios')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[ 31  10]
 [941 778]]

precision del modelo: 
0.9873096446700508

exactitud del modelo
0.4596590909090909

sensibilidad del modelo: 
0.4525887143688191


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Yael David

In [51]:
#convertimos una variable categorica  dicotomica
usuario_2['Usuario']= usuario_2['Usuario'].replace([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_2['Usuario']= usuario_2['Usuario'].replace([11], 'Yael David')


In [62]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_2[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_2[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='demás usuarios')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='demás usuarios')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[ 37  18]
 [791 914]]

precision del modelo: 
0.98068669527897

exactitud del modelo
0.540340909090909

sensibilidad del modelo: 
0.5360703812316715


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Yeremy Jazmin

In [53]:
#convertimos una variable categorica  dicotomica
usuario_3['Usuario']= usuario_3['Usuario'].replace([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10,11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 25, 26, 27, 28, 29, 30, 31, 32], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_3['Usuario']= usuario_3['Usuario'].replace([24], 'Yeremy jazmin')


In [63]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_3[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_3[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='demás usuarios')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='demás usuarios')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[ 15   8]
 [790 947]]

precision del modelo: 
0.9916230366492147

exactitud del modelo
0.5465909090909091

sensibilidad del modelo: 
0.5451928612550374


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Ramiro

In [55]:
#convertimos una variable categorica  dicotomica
usuario_4['Usuario']= usuario_4['Usuario'].replace([ 0,  1,  2,  3,  4,  5, 7,  8,  9, 10,11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,24, 25, 26, 27, 28, 29, 30, 31, 32], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_4['Usuario']= usuario_4['Usuario'].replace([6], 'Ramiro')


In [64]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_4[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_4[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='demás usuarios')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='demás usuarios')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[ 51  16]
 [973 720]]

precision del modelo: 
0.9782608695652174

exactitud del modelo
0.4380681818181818

sensibilidad del modelo: 
0.42528056704075606


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


### Irving 

In [57]:
#convertimos una variable categorica  dicotomica
usuario_5['Usuario']= usuario_5['Usuario'].replace([ 0,  1,  2,  3,  4,  5,6, 7,  8,  9, 10,11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23,24, 25, 26, 27, 28, 29, 30, 31], 'demás usuarios')

#convertimos una variable categorica  dicotomica
usuario_5['Usuario']= usuario_5['Usuario'].replace([32], 'Irving')


In [65]:
#Declaramos las variables dependientes e independietes para la regresión lineal 
vars_Indep=usuario_5[['tiempo de interacción', 'botón correcto', 'número de interacción']]
vars_Dep=usuario_5[['Usuario']]

#Redefinimos las variables
X= vars_Indep
y= vars_Dep

#Dividimos el conjunto de datos en la parte de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)

#Se escalan todos los datos : Escalr es como si pasaran los datos a una sola escala en porcentajes, como una regla de tres 
escalar = StandardScaler()

#Para realuzar el escalamiento de las variables "X" tanto en entrenamiento como de prueba utilizaremos:
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression(class_weight='balanced')

#Entrenamos el modelo

algoritmo.fit(X_train, y_train)

y_pred = algoritmo.predict(X_test) #Predecimos los datos de test
y_pred

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de confusión: ')
print(matriz)
print('')

#Calculo la precisión de mmodelo

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average='binary', pos_label ='demás usuarios')
print('precision del modelo: ')
print(precision)
print('')


#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print('exactitud del modelo')
print(exactitud)
print('')


#calculamos la sensibilidad del modelo
from sklearn.metrics import recall_score

sensibilidad = recall_score(y_test, y_pred, average='binary', pos_label='demás usuarios')
print('sensibilidad del modelo: ')
print(sensibilidad)

Matriz de confusión: 
[[   1    0]
 [ 511 1248]]

precision del modelo: 
1.0

exactitud del modelo
0.709659090909091

sensibilidad del modelo: 
0.709494030699261


c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
